name: pacman

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: RohitSah04
